name: Build, Scan, and Push

on:
  push:
    branches:
      - main
      - master

jobs:
  build_scan_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"
      - name: Run Dagger Pipeline
        run: ./run_ci.sh -all
        env:
          GITHUB_TOKEN: ${{ github.token }}
